services:
  database:
    container_name: database
    image: mysql
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
  application:
    container_name: app
    depends_on:
      - database
    image: dstoya/restful-movies:latest
    ports:
      - "8080:8080"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
      DB_HOST: database
#TODO ADD ENV FILE/VARS
volumes:
  data:

