spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${MYSQL_PASSWORD:123}
    username: ${MYSQL_USER:root}
    url: jdbc:mysql://${DB_HOST:localhost}:3306/restful_movies?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
  jpa:
    #        hibernate:
    #          ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        globally_quoted_identifiers: true
        hbm2ddl:
          auto: create-drop
    #        show_sql: true
    #        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

app:
  security:
    jwt:
      secretKey: 462D4A614E645267556B58703273357638792F423F4528472B4B625065536856
      expiration: 60000 # 1m
      refreshToken:
        expiration: 1800000 # 30m