name: Build & Deploy
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Pull source code
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Setup Gradle and run 'test'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Pull source code
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Setup Gradle and run 'build'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Upload build files
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          # change with file name if error
          path: |
            build/libs/*.jar 
            Dockerfile

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build files
        uses: actions/download-artifact@v3
        with:
          name: build-files
      - name: Docker set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Docker set up Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          # add dockerFile if fails
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/restful-movies:latest




